import { defineNuxtModule, addTypeTemplate } from '@nuxt/kit'

export default defineNuxtModule({
    setup(_options, nuxt) {
      addTypeTemplate({
        filename: 'types/my-module.d.ts',
        getContents: () => `// Generated by my-module
          declare module 'nuxt/schema' {
            interface NuxtConfig {
              name: string
            }
          }
          export {}`
      })
      console.log('test')
      // for (const layer of nuxt.options._layers) {
      //   // You can check for a custom directory existence to extend for each layer
      //   console.log(layer.config.name)
      // }
    }
})
